name: build-test-deploy2

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: installing node
        run: npm install
        working-directory: ./06_Bookstore/TekBooks
      - name: build
        run: npm run build
        working-directory: ./06_Bookstore/TekBooks
